// vue-js-example/focustrap-example/src/App.vue
<template>
<h1> Vue 3 Focus Trap Example </h1>
  <div>
    <button @click="openModal">Open Modal</button>
    <div v-if="isModalOpen" id="myElement" class="modal-overlay" @click="closeModal">
      <div class="modal-container" ref="modalContainer">
        <button @click="closeModal">Close Modal</button>
        <p>I am a div with class "modal-container"</p>
        <button>First Button</button>
        <button>Second Button</button>
        <button>Third Button</button>
        <input />
      </div>
    </div>
  </div>

  <button>After Trap</button>
</template>

<script>
 import { focusTrap } from 'magicthecat-trapfocus/index'



export default {
  data() {
    return {
      isModalOpen: false,
    };
  },
  methods: {
    openModal() {
      this.isModalOpen = true;
      this.$nextTick(() => {
        this.$refs.modalContainer.focus();
        this.removeTrap = focusTrap(this.$refs.modalContainer);
      });
    },
    closeModal() {
      this.isModalOpen = false;
      if (this.removeTrap) {
        this.removeTrap();
      }
    },
  },
  beforeUnmount() {
    if (this.removeTrap) {
      this.removeTrap();
    }
  },
};
</script>

// react-example/trapfocus-example/src/App.js
import './App.css';
import { focusTrap } from 'magicthecat-trapfocus'
import React, { useEffect, useRef, useState } from 'react';
const Modal = () => {
  const [isOpen, setIsOpen] = useState(false);

  const toggleModal = () => {
    setIsOpen(!isOpen);
  };

  const closeModal = () => {
    setIsOpen(false);
  };

  return (
    <>
      <button onClick={toggleModal}>Open Modal</button>
      {isOpen && (
        <div id="myElement">
          <FocusTrap>
            <div id="modalBackground" onClick={closeModal} />
            <button onClick={closeModal}>Close Modal</button>
            <p>I am a div with id "myElement"</p>
            <button>First Button</button>
            <button>Second Button</button>
            <button>Third Button</button>
            <input />
          </FocusTrap>
        </div>
      )}
    </>
  );
};

function FocusTrap({ children }) {
  const trapRef = useRef(null);

  useEffect(() => {
    if (trapRef.current) {
      const removeFocusTrap = focusTrap(trapRef.current);
      return () => {
        removeFocusTrap();
      };
    }
  }, []);

  return (
    <div ref={trapRef}>
      {children}
    </div>
  );
}


function App() {
  return (
    <div className="App">
      <h1>React Example</h1>

      <Modal />
      <p>hello</p>
    </div>
  );
}

export default App;
